server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.100.164.178:3306/springcloud?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: spider
    password: spider112
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.hwt.entity.pojo

logging:
  level:
    root: info
    com.hwt.spider.mapper: debug