server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.100.164.178:3306/springcloud?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: spider
    password: spider112
  cloud:
    consul:
      host: 47.100.164.178
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 47.100.164.178
        heartbeat:
          enabled: true
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.hwt.entity.pojo