server:
  port: 80

spring:
  application:
    name: cloud-consul-order

  cloud:
    consul:
      host: 47.100.164.178
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 47.100.164.178
        heartbeat:
          enabled: true